// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNgyCJOpEQjh-iVuKJyn09o_eE8QuDCss',
    appId: '1:20771513506:web:8eb137279f97b2afe0e3fb',
    messagingSenderId: '20771513506',
    projectId: 'green-watch-fed48',
    authDomain: 'green-watch-fed48.firebaseapp.com',
    storageBucket: 'green-watch-fed48.firebasestorage.app',
    measurementId: 'G-DHQQTGBR9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIfV-IowxUSjqrlEJ6nirSYISVND-1LxI',
    appId: '1:20771513506:android:d3b58901ed6c1ca1e0e3fb',
    messagingSenderId: '20771513506',
    projectId: 'green-watch-fed48',
    storageBucket: 'green-watch-fed48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxUjR0DUEZMfV0Aywjd_Ml5y3ukzNEhCk',
    appId: '1:20771513506:ios:1945cf127624f7c7e0e3fb',
    messagingSenderId: '20771513506',
    projectId: 'green-watch-fed48',
    storageBucket: 'green-watch-fed48.firebasestorage.app',
    iosBundleId: 'com.example.greenWatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxUjR0DUEZMfV0Aywjd_Ml5y3ukzNEhCk',
    appId: '1:20771513506:ios:1945cf127624f7c7e0e3fb',
    messagingSenderId: '20771513506',
    projectId: 'green-watch-fed48',
    storageBucket: 'green-watch-fed48.firebasestorage.app',
    iosBundleId: 'com.example.greenWatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNgyCJOpEQjh-iVuKJyn09o_eE8QuDCss',
    appId: '1:20771513506:web:9d0f75dcb9fd491ae0e3fb',
    messagingSenderId: '20771513506',
    projectId: 'green-watch-fed48',
    authDomain: 'green-watch-fed48.firebaseapp.com',
    storageBucket: 'green-watch-fed48.firebasestorage.app',
    measurementId: 'G-RJX9CDLD5R',
  );

}